name: Start Docker Image CI

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  pull-and-run-docker-image:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: pull docker image
      run: docker pull vovantrong/social-frontend:latest
      
    - name: stop docker container
      run: docker stop social-frontend || true && docker rm social-frontend || true
      
    - name: run docker image
      run: docker run -p 3000:80/tcp -d --name social-frontend vovantrong/social-frontend:latest
